#!/bin/bash
# build-install.sh — generate a self-contained install.sh
#
# Embeds the current source files (statusline.sh, my-usd.sh, my-tokens.sh,
# commands/my-usd.md, commands/my-tokens.md) into a single install.sh, so users
# can install with a
# one-line `curl … | bash` and no git clone. The repo stays the source of
# truth: edit the source files, then re-run this to regenerate install.sh.
set -euo pipefail

REPO="$(cd "$(dirname "$0")" && pwd)"
OUT="$REPO/install.sh"

# Append a `cat > <dest> <<'DELIM' … DELIM` block that writes $src verbatim.
embed() {
  local src="$1" dest="$2" delim="$3"
  [ -f "$REPO/$src" ] || { echo "Error: missing source $src" >&2; exit 1; }
  if grep -qxF "$delim" "$REPO/$src"; then
    echo "Error: heredoc delimiter '$delim' appears literally in $src — pick another." >&2
    exit 1
  fi
  {
    printf "cat > %s <<'%s'\n" "$dest" "$delim"
    cat "$REPO/$src"
    printf '%s\n' "$delim"
  } >> "$OUT"
}

# ---------------------------------------------------------------- header ----
cat > "$OUT" <<'HEADER'
#!/bin/bash
# Self-contained installer for the Claude Code status line.
#
# GENERATED by build-install.sh — do not edit by hand. Edit the source files
# (statusline.sh, my-usd.sh, my-tokens.sh, commands/*.md) and re-run
# ./build-install.sh.
#
# Install with either:
#   ./install.sh
#   curl -fsSL https://raw.githubusercontent.com/guptesachin/claude-statusline/main/install.sh | bash
set -euo pipefail

CLAUDE_DIR="$HOME/.claude"
SETTINGS="$CLAUDE_DIR/settings.json"

command -v jq >/dev/null 2>&1 || { echo "Error: jq is required but not found. Install it (e.g. 'brew install jq') and retry."; exit 1; }

mkdir -p "$CLAUDE_DIR" "$CLAUDE_DIR/commands"

# 1. Status line script
HEADER

embed statusline.sh '"$CLAUDE_DIR/statusline.sh"' 'CLAUDE_STATUSLINE_EOF'

cat >> "$OUT" <<'MID1'
chmod +x "$CLAUDE_DIR/statusline.sh"
echo "Installed $CLAUDE_DIR/statusline.sh"

# 1b. Usage/spend report
MID1

embed my-usd.sh '"$CLAUDE_DIR/my-usd.sh"' 'CLAUDE_MYUSD_EOF'

cat >> "$OUT" <<'MID2'
chmod +x "$CLAUDE_DIR/my-usd.sh"
echo "Installed $CLAUDE_DIR/my-usd.sh"

# 1c. /my-usd slash command
MID2

embed commands/my-usd.md '"$CLAUDE_DIR/commands/my-usd.md"' 'CLAUDE_MYUSDCMD_EOF'

cat >> "$OUT" <<'MID3'
echo "Installed $CLAUDE_DIR/commands/my-usd.md  (use /my-usd in Claude Code)"

# 1d. Token usage report
MID3

embed my-tokens.sh '"$CLAUDE_DIR/my-tokens.sh"' 'CLAUDE_MYTOKENS_EOF'

cat >> "$OUT" <<'MID4'
chmod +x "$CLAUDE_DIR/my-tokens.sh"
echo "Installed $CLAUDE_DIR/my-tokens.sh"

# 1e. /my-tokens slash command
MID4

embed commands/my-tokens.md '"$CLAUDE_DIR/commands/my-tokens.md"' 'CLAUDE_MYTOKENSCMD_EOF'

cat >> "$OUT" <<'FOOTER'
echo "Installed $CLAUDE_DIR/commands/my-tokens.md  (use /my-tokens in Claude Code)"

# 2. Wire up settings.json (creating it if absent)
[ -f "$SETTINGS" ] || echo '{}' > "$SETTINGS"

if jq -e '.statusLine' "$SETTINGS" >/dev/null 2>&1; then
  echo "A 'statusLine' setting already exists in $SETTINGS — leaving it untouched."
  echo "To use this one, set its command to: ~/.claude/statusline.sh"
  exit 0
fi

cp "$SETTINGS" "$SETTINGS.bak"
tmp="$(mktemp)"
jq '. + {statusLine: {type: "command", command: "~/.claude/statusline.sh"}}' "$SETTINGS" > "$tmp"
mv "$tmp" "$SETTINGS"
echo "Updated $SETTINGS (backup at $SETTINGS.bak)"
echo "Done. Start a new Claude Code session to see your status line."
FOOTER

chmod +x "$OUT"
echo "Generated $OUT"
