#!/bin/bash
# Self-contained installer for the Claude Code status line.
#
# GENERATED by build-install.sh — do not edit by hand. Edit the source files
# (statusline.sh, my-usd.sh, my-tokens.sh, commands/*.md) and re-run
# ./build-install.sh.
#
# Install with either:
#   ./install.sh
#   curl -fsSL https://raw.githubusercontent.com/guptesachin/claude-statusline/main/install.sh | bash
set -euo pipefail

CLAUDE_DIR="$HOME/.claude"
SETTINGS="$CLAUDE_DIR/settings.json"

command -v jq >/dev/null 2>&1 || { echo "Error: jq is required but not found. Install it (e.g. 'brew install jq') and retry."; exit 1; }

mkdir -p "$CLAUDE_DIR" "$CLAUDE_DIR/commands"

# 1. Status line script
cat > "$CLAUDE_DIR/statusline.sh" <<'CLAUDE_STATUSLINE_EOF'
#!/bin/bash
# Claude Code Status Line
# Shows: model | tokens (%) | cost | running sessions
#
# Claude Code pipes a JSON object into this script on stdin and renders
# whatever it prints on stdout as the status line.
#
# Requires: jq  (https://jqlang.github.io/jq/)

DATA=$(cat)

# --- Extract fields via jq ---------------------------------------------------
MODEL=$(echo "$DATA" | jq -r '.model.display_name // "N/A"')
CTX_PCT=$(echo "$DATA" | jq -r '.context_window.used_percentage // 0')
COST=$(echo "$DATA" | jq -r '.cost.total_cost_usd // 0')

# Used tokens in thousands, total context window in millions
USED_K=$(echo "$DATA" | jq -r '(.context_window.context_window_size // 0) * (.context_window.used_percentage // 0) / 100 / 1000 | floor')
TOTAL_M=$(echo "$DATA" | jq -r '(.context_window.context_window_size // 0) / 1000000')

# --- Log this session's stats for `my-usd.sh` / `/my-usd` --------------------
# One file per session_id, overwritten on each refresh, so each file always
# holds that session's latest cumulative totals (cost, tokens, lines). Summing
# across files = your all-time totals, with no double-counting. Safe to remove
# this block if you only want the status bar and not the spend report.
SESSION_ID=$(echo "$DATA" | jq -r '.session_id // empty')
if [ -n "$SESSION_ID" ]; then
  LOG_DIR="$HOME/.claude/session-logs"
  mkdir -p "$LOG_DIR" 2>/dev/null
  echo "$DATA" | jq -c '{
    model: (.model.display_name // "N/A"),
    model_id: (.model.id // "N/A"),
    context_used_k: ((.context_window.context_window_size // 0) * (.context_window.used_percentage // 0) / 100 / 1000 | floor),
    context_total_m: ((.context_window.context_window_size // 0) / 1000000),
    context_pct: (.context_window.used_percentage // 0),
    cost_usd: (.cost.total_cost_usd // 0),
    duration_ms: (.cost.total_duration_ms // 0),
    lines_added: (.cost.total_lines_added // 0),
    lines_removed: (.cost.total_lines_removed // 0),
    total_input_tokens: (.context_window.total_input_tokens // 0),
    total_output_tokens: (.context_window.total_output_tokens // 0),
    cwd: (.cwd // "N/A"),
    updated_at: now
  }' > "$LOG_DIR/$SESSION_ID.json" 2>/dev/null
fi

# --- Count running Claude Code sessions --------------------------------------
# Claude Code writes one JSON file per session to ~/.claude/sessions/ with a
# `pid` field. `kill -0` tests whether that process is still alive.
RUNNING=0
for f in "$HOME"/.claude/sessions/*.json; do
  [ -f "$f" ] || continue
  pid=$(jq -r '.pid' "$f" 2>/dev/null)
  if kill -0 "$pid" 2>/dev/null; then
    RUNNING=$((RUNNING + 1))
  fi
done

echo "${MODEL} | ${USED_K}k/${TOTAL_M}m tokens (${CTX_PCT}%) | \$${COST} | ${RUNNING} sessions"
CLAUDE_STATUSLINE_EOF
chmod +x "$CLAUDE_DIR/statusline.sh"
echo "Installed $CLAUDE_DIR/statusline.sh"

# 1b. Usage/spend report
cat > "$CLAUDE_DIR/my-usd.sh" <<'CLAUDE_MYUSD_EOF'
#!/bin/bash
# my-usd.sh — summarize Claude Code usage & estimated spend
#
# Reads the per-session logs written by statusline.sh
# (~/.claude/session-logs/*.json) and prints:
#   - all-time and rolling-window estimated spend
#   - a spend-by-model breakdown
#   - your most recent sessions
#
# For token counts rather than dollars, see my-tokens.sh (/my-tokens).
#
# NOTE: cost_usd is Claude Code's *estimate* of API-equivalent cost. On a
# Pro/Max subscription you don't pay this directly; treat it as a usage signal.
#
# Requires: jq
set -euo pipefail

LOG_DIR="$HOME/.claude/session-logs"
command -v jq >/dev/null 2>&1 || { echo "jq is required."; exit 1; }

shopt -s nullglob
LOGS=("$LOG_DIR"/*.json)
if [ ${#LOGS[@]} -eq 0 ]; then
  echo "No session logs yet at $LOG_DIR."
  echo "They start accumulating once statusline.sh has run in a session."
  exit 0
fi

# Current time (epoch seconds). Passed into jq so all math stays in one place.
NOW=$(date +%s)

# ------------------------------------------------------------------ totals ----
echo "=== Claude Code usage summary ==="
jq -rs --argjson now "$NOW" '
  def since($secs): map(select(.updated_at >= ($now - $secs)));
  def usd: "$" + (.*100|round/100|tostring);
  # NOTE: cost is the reliable per-session cumulative metric. The token fields
  # in these logs are point-in-time context snapshots, NOT cumulative usage, so
  # we do not sum them here — run /my-tokens for real cumulative token usage.
  "Sessions logged : \(length)",
  "Last 24 hours   : \(since(86400)   | map(.cost_usd) | add // 0 | usd)",
  "Last 7 days     : \(since(604800)  | map(.cost_usd) | add // 0 | usd)",
  "Last 30 days    : \(since(2592000) | map(.cost_usd) | add // 0 | usd)",
  "All-time (est.) : \(map(.cost_usd) | add | usd)"
' "${LOGS[@]}"

# --------------------------------------------------------------- by model ----
echo
echo "=== Spend by model (all-time, est.) ==="
jq -rs '
  group_by(.model)
  | map({model: .[0].model, sessions: length, cost: (map(.cost_usd)|add)})
  | sort_by(-.cost)[]
  | "\(.cost | .*100|round/100 | tostring | (" "*(9-length)) + .)  \(.sessions | tostring | (" "*(4-length)) + .)  \(.model)"
' "${LOGS[@]}" | { printf "%9s  %4s  %s\n" "USD" "N" "MODEL"; cat; }

# ------------------------------------------------------- recent sessions ----
echo
echo "=== 10 most recent sessions ==="
jq -rs --argjson now "$NOW" '
  sort_by(-.updated_at)[:10][]
  | "\(.cost_usd | .*100|round/100 | tostring | (" "*(8-length)) + .)  \(.context_pct|tostring + "%" | (" "*(4-length)) + .)  \(((($now - .updated_at)/3600) | if . < 0 then 0 else . end | floor))h ago  \(.cwd | split("/") | last)"
' "${LOGS[@]}" | { printf "%8s  %4s  %-9s %s\n" "USD" "CTX" "WHEN" "PROJECT"; cat; }
CLAUDE_MYUSD_EOF
chmod +x "$CLAUDE_DIR/my-usd.sh"
echo "Installed $CLAUDE_DIR/my-usd.sh"

# 1c. /my-usd slash command
cat > "$CLAUDE_DIR/commands/my-usd.md" <<'CLAUDE_MYUSDCMD_EOF'
---
description: Summarize Claude Code usage and estimated spend across all sessions
allowed-tools: Bash(~/.claude/my-usd.sh)
---

Run `~/.claude/my-usd.sh` and show the user its full output verbatim in a
code block. Then add a one-line takeaway: their rolling 30-day estimated spend
and whether it is trending up or down versus the prior period, if the numbers
support saying so.

Remind them briefly that `cost_usd` is Claude Code's *estimate* of
API-equivalent cost — on a Pro/Max subscription it reflects usage, not an
actual bill.
CLAUDE_MYUSDCMD_EOF
echo "Installed $CLAUDE_DIR/commands/my-usd.md  (use /my-usd in Claude Code)"

# 1d. Token usage report
cat > "$CLAUDE_DIR/my-tokens.sh" <<'CLAUDE_MYTOKENS_EOF'
#!/bin/bash
# my-tokens.sh — summarize Claude Code token usage across all sessions
#
# Reads the session transcripts at ~/.claude/projects/**/*.jsonl and prints:
#   - rolling-window and all-time token totals
#   - a tokens-by-model breakdown (input / output / cache write / cache read)
#   - your most recent sessions by token volume
#
# This is the companion to my-usd.sh: that one owns dollars, this one owns
# tokens. They read different data sources on purpose — the per-session logs
# my-usd.sh reads only carry point-in-time *context window* snapshots, which
# are not cumulative and cannot be summed. True usage lives in the transcripts.
#
# Three things this script has to get right, all verified against real data:
#   1. Dedup on requestId. Claude Code writes one JSONL record per content
#      block, so a thinking+text+tool_use response is three records sharing one
#      identical usage object. Summing naively inflates totals ~2.15x.
#   2. Find, not globs. Transcripts nest three levels deep in three different
#      shapes (session, subagents/, subagents/workflows/wf_*/); a fixed-depth
#      glob silently misses the last one.
#   3. Skip <synthetic> records — local API-error placeholders with zero usage.
#
# Requires: jq
set -euo pipefail

PROJECTS="$HOME/.claude/projects"
command -v jq >/dev/null 2>&1 || { echo "jq is required."; exit 1; }
[ -d "$PROJECTS" ] || { echo "No transcripts found at $PROJECTS."; exit 0; }

# Current time (epoch seconds), passed into awk so all the window math is in
# one place.
NOW=$(date +%s)

# jq flattens each assistant record to a TSV row; awk dedups and aggregates.
# /dev/null is passed as a guaranteed input file: GNU xargs runs its command
# even on empty input, and a jq with no file arguments would sit reading stdin.
# `|| true` keeps one corrupt transcript line from failing the whole report
# under `set -o pipefail` — jq skips the bad line and we still print the rest.
{ find "$PROJECTS" -name '*.jsonl' -print0 | xargs -0 jq -r '
  select(.type=="assistant" and (.message.usage|type)=="object")
  | select((.message.model // "") != "<synthetic>")
  | [ (.requestId // .message.id // "?"),
      ((.timestamp // "1970-01-01T00:00:00Z") | sub("\\.[0-9]+Z$";"Z") | fromdateiso8601),
      (.message.model // "unknown"),
      (.message.usage.input_tokens // 0),
      (.message.usage.output_tokens // 0),
      (.message.usage.cache_creation_input_tokens // 0),
      (.message.usage.cache_read_input_tokens // 0),
      (.sessionId // "?"),
      ((.cwd // "?") | split("/") | last)
    ] | @tsv' /dev/null 2>/dev/null || true; } \
| awk -F'\t' -v now="$NOW" '
# Format a raw token count as 1.71B / 532.35M / 4.78k. Token counts run to
# billions, so every number in this report goes through here — do not pad
# these by hand the way my-usd.sh does, it breaks once a value outgrows its
# column.
function h(n,  u,i) { split(",k,M,B,T", u, ",")
  i=1; while (n >= 1000 && i < 5) { n/=1000; i++ }
  return (i==1) ? sprintf("%d", n) : sprintf("%.2f%s", n, u[i]) }

# seen[] is the dedup gate: first record of a requestId wins, the rest are
# repeats of the same API response and must not be counted again.
!seen[$1]++ {
  t=$2; m=$3; iin=$4; out=$5; cw=$6; cr=$7; sid=$8; proj=$9
  tot=iin+out+cw+cr; age=now-t
  if (age<=86400)   T24+=tot
  if (age<=604800)  T7+=tot
  if (age<=2592000) T30+=tot
  ALL+=tot; IN+=iin; OUT+=out; CW+=cw; CR+=cr
  M[m]+=tot; MR[m]++; MI[m]+=iin; MO[m]+=out; MW[m]+=cw; MC[m]+=cr
  # Records inside subagents/ carry the parent sessionId, so subagent tokens
  # roll up into their session for free.
  S[sid]+=tot; if (t>ST[sid]) ST[sid]=t; SP[sid]=proj
  n++
}

END {
  if (n == 0) { print "No token usage found in transcripts."; exit }

  printf "=== Claude Code token usage ===\n"
  printf "Requests logged : %d\n", n
  printf "Sessions        : %d\n", length(S)
  printf "Last 24 hours   : %s\n", h(T24)
  printf "Last 7 days     : %s\n", h(T7)
  printf "Last 30 days    : %s\n", h(T30)
  printf "All-time        : %s\n", h(ALL)
  # --- derived efficiency metric ------------------------------------------
  # The one number a reader looks at first. Swap this for whichever signal you
  # actually want: CR/(CR+CW) is a truer cache hit rate, OUT/n is average work
  # per turn, ALL/length(S) is average tokens per session.
  printf "Cache reads     : %.1f%% of all input tokens\n", 100*CR/(IN+CW+CR)

  printf "\n=== Tokens by model (all-time) ===\n"
  printf "%9s %6s %9s %9s %9s %10s  %s\n","TOTAL","REQS","IN","OUT","CACHE_W","CACHE_R","MODEL"
  # Sort on a hidden raw-number first field, then cut it away. Sorting the
  # formatted column with `sort -h` is unreliable across BSD and GNU.
  srt="sort -t\"\t\" -k1,1rn | cut -f2-"
  for (m in M) printf "%d\t%9s %6d %9s %9s %9s %10s  %s\n", M[m], h(M[m]), MR[m], h(MI[m]), h(MO[m]), h(MW[m]), h(MC[m]), m | srt
  close(srt)

  printf "\n=== 10 most recent sessions ===\n"
  printf "%9s  %-8s %s\n","TOTAL","WHEN","PROJECT"
  srt2="sort -t\"\t\" -k1,1rn | head -10 | cut -f2-"
  for (s in S) { a=int((now-ST[s])/3600); if (a<0) a=0
    printf "%d\t%9s  %-8s %s\n", ST[s], h(S[s]), a "h ago", SP[s] | srt2 }
  close(srt2)
}'
CLAUDE_MYTOKENS_EOF
chmod +x "$CLAUDE_DIR/my-tokens.sh"
echo "Installed $CLAUDE_DIR/my-tokens.sh"

# 1e. /my-tokens slash command
cat > "$CLAUDE_DIR/commands/my-tokens.md" <<'CLAUDE_MYTOKENSCMD_EOF'
---
description: Summarize Claude Code token usage across all sessions
allowed-tools: Bash(~/.claude/my-tokens.sh)
---

Run `~/.claude/my-tokens.sh` and show the user its full output verbatim in a
code block. Then add a one-line takeaway about where their tokens are going —
which model or project dominates, and how the 7-day figure compares against a
seventh of the 30-day figure, if the numbers support saying so.

Note briefly that cache reads dominate these totals and are billed at a
fraction of fresh input tokens, so token volume is *not* proportional to
spend — `/my-usd` is the command for dollars.
CLAUDE_MYTOKENSCMD_EOF
echo "Installed $CLAUDE_DIR/commands/my-tokens.md  (use /my-tokens in Claude Code)"

# 2. Wire up settings.json (creating it if absent)
[ -f "$SETTINGS" ] || echo '{}' > "$SETTINGS"

if jq -e '.statusLine' "$SETTINGS" >/dev/null 2>&1; then
  echo "A 'statusLine' setting already exists in $SETTINGS — leaving it untouched."
  echo "To use this one, set its command to: ~/.claude/statusline.sh"
  exit 0
fi

cp "$SETTINGS" "$SETTINGS.bak"
tmp="$(mktemp)"
jq '. + {statusLine: {type: "command", command: "~/.claude/statusline.sh"}}' "$SETTINGS" > "$tmp"
mv "$tmp" "$SETTINGS"
echo "Updated $SETTINGS (backup at $SETTINGS.bak)"
echo "Done. Start a new Claude Code session to see your status line."
